# Warm-Up: Rechnen mit Matrizen und Vektoren in Python

## Aufgabe 1: Ohne externe Libraries zu lösen

a) Berechnen Sie das Skalarprodukt von Vektor `v1 = [1 2 3 4 5]` und `v2 = [6 7 8 9 10]`

In [4]:
#Lösung
v1 = [1,2,3,4,5]
v2 = [6,7,8,9,10]

print(sum(map(lambda x,y: x*y,v1,v2)))

130


b) Multiplizieren Sie folgende Matrix `m` mit Vektor `v1`:
    
    [[ 1  2  3  4  5]
    [ 6  7  8  9 10]]

In [5]:
#Lösung

m = [[1,2,3,4,5],[6,7,8,9,10]]

print([sum(map(lambda x,y: x*y,row,v1)) for row in m])

[55, 130]


## Aufgabe 2: Mit Library numpy zu lösen

In [2]:
import numpy as np

a) Lösen Sie Aufgabe 1a) mithilfe von numpy

In [6]:
#Lösung
npv1 = np.array(v1)
npv2 = np.array(v2)

print(np.dot(npv1, npv2))

130


b) Lösen Sie Aufgabe 1b) mithilfe von numpy

In [7]:
#Lösung
npm1 = np.matrix(m)

print(npm1.dot(npv1))

[[ 55 130]]


c) Erstellen Sie mithilfe von numpy-Funktionen folgende Matrizen, ohne zuvor manuell Listen anzulegen:

    m1: [[0. 0. 0. 0. 0.]
         [0. 0. 0. 0. 0.]
         [0. 0. 0. 0. 0.]]

    m2: [[1. 1. 1.]
         [1. 1. 1.]
         [1. 1. 1.]
         [1. 1. 1.]
         [1. 1. 1.]]

    m3: [[ 1  2  3  4  5]
        [ 6  7  8  9 10]]

    m4: [[ 100  200]
         [ 300  400]
         [ 500  600]
         [ 700  800]
         [ 900 1000]]


In [19]:
#Lösung
m1c = np.zeros((3,5))
print(m1c)

m2c = np.ones((5,3))
print(m2c)

m3c = np.arange(1, 11).reshape((2,5))
print(m3c)

m4c = np.arange(100, 1001, 100).reshape((5,2))
print(m4c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 100  200]
 [ 300  400]
 [ 500  600]
 [ 700  800]
 [ 900 1000]]


d) Multiplizieren Sie Matrix `m3` mit `m4` und danach `m4` mit `m3`.
Überlegen Sie jeweils vorab, wie viele Zeilen und Spalten das Ergebnis haben wird.

In [7]:
#Lösung
